[build]
builder = "nixpacks"
buildCommand = "bun install"

[deploy]
startCommand = "sh scripts/startup.sh"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"

[nixpacks]
nodejs-version = "20"
